--liquibase formatted sql
--changeset ks-spoda:1.0

create TABLE "SEASON" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "LEAGUE_ID" NUMBER(10) NOT NULL,
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE NULL,
    "INITIAL_RATING" NUMBER(10,2) NULL,
    "IS_FINISHED" NUMBER(1) NULL,
    "POINT_COUNTING_METHOD" VARCHAR(20) NOT NULL,
    "RATING_TYPE"  VARCHAR(10) NULL,
    "LEAGUE_SEASON_COUNT" NUMBER(2) NOT NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);
