--liquibase formatted sql
--changeset ks-spoda:1.0

create TABLE "MATCH_GAME" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "MATCH_DAY_ID" NUMBER(10) NOT NULL,
    "MATCH_TIME" DATETIME NOT NULL,
    "HOME_TEAM_ID" NUMBER(10) NULL,
    "AWAY_TEAM_ID" NUMBER(10) NULL,
    "HOME_GOALS" NUMBER(2) NOT NULL,
    "AWAY_GOALS" NUMBER(2) NOT NULL,
    "IS_FINISHED" NUMBER(1) NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "MATCH_TEAM" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "GAME_TEAM_ID" NUMBER(10) NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "PLAYER" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(30) NOT NULL,
    "ALIAS" VARCHAR(30) NULL,
    "PLAYER_IMG" BLOB NULL,
    "STATUS" VARCHAR(10) NULL,
    "DESCRIPTION" VARCHAR(200) NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "GAME_TEAM" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "SHORT_NAME" VARCHAR(50) NULL,
    "ALIAS" VARCHAR(50) NULL,
    "OVERALL_RATING" NUMBER(10) NOT NULL,
    "BADGE_IMG" VARCHAR(250) NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "SEASON_TABLE" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "SEASON_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "CURRENT_RATING" NUMBER(10,2) NULL,
    "CURRENT_POSITION" NUMBER(3) NOT NULL,
    "PREVIOUS_POSITION" NUMBER(3) NOT NULL,
    "STANDBY_POSITION" NUMBER(3) NULL,
    "MATCHES" NUMBER(5) NOT NULL,
    "POINTS_TOTAL" NUMBER(5) NOT NULL,
    "MATCH_IN_PROGRESS" NUMBER(1) NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "LEAGUE_TABLE" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "LEAGUE_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "CURRENT_RATING" NUMBER(10,2) NOT NULL,
    "CURRENT_POSITION" NUMBER(3) NOT NULL,
    "PREVIOUS_POSITION" NUMBER(3) NOT NULL,
    "STANDBY_POSITION" NUMBER(3) NULL,
    "MATCHES" NUMBER(5) NOT NULL,
    "POINTS_TOTAL" NUMBER(5) NOT NULL,
    "MATCH_IN_PROGRESS" NUMBER(1) NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "MATCH_DAY_TABLE" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "MATCH_DAY_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "CURRENT_RATING" NUMBER(10,2) NULL,
    "CURRENT_POSITION" NUMBER(3) NOT NULL,
    "PREVIOUS_POSITION" NUMBER(3) NOT NULL,
    "STANDBY_POSITION" NUMBER(3) NULL,
    "MATCHES" NUMBER(5) NOT NULL,
    "POINTS_TOTAL" NUMBER(5) NOT NULL,
    "MATCH_IN_PROGRESS" NUMBER(1) NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "MATCH_DETAILS" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "MATCH_ID" NUMBER(10) NOT NULL,
    "MATCH_DAY_ID" NUMBER(10) NOT NULL,
    "SEASON_ID" NUMBER(10) NOT NULL,
    "LEAGUE_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "MATCH_POINTS" NUMBER(5) NOT NULL,
    "GOALS_SCORED" NUMBER(5) NOT NULL,
    "GOALS_CONCEDED" NUMBER(5) NOT NULL,
    "MATCH_RESULT" VARCHAR(5) NOT NULL,
    "LEAGUE_RATING_BEFORE_MATCH" NUMBER(10,2) NULL,
    "LEAGUE_RATING_AFTER_MATCH" NUMBER(10,2) NULL,
    "SEASON_RATING_BEFORE_MATCH" NUMBER(10,2) NULL,
    "SEASON_RATING_AFTER_MATCH" NUMBER(10,2) NULL,
    "MATCH_DAY_RATING_BEFORE_MATCH" NUMBER(10,2) NULL,
    "MATCH_DAY_RATING_AFTER_MATCH" NUMBER(10,2) NULL,
    "MATCH_IN_PROGRESS" NUMBER(1) NOT NULL,
    "CREATION_DATE" DATETIME NOT NULL,
    "LAST_MODIFICATION_DATE" DATETIME NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

