spring:
  profiles:
    active: dev
  config:
    import:
      - classpath:config/database.yaml
  liquibase:
    change-log: classpath:database/changelog/changelog-master.yaml

base.request: "/api/v1"