spring:
  config:
    import:
      - classpath:database-config.yaml

base.request: "/api/v1"
application:
  initial-rating: "1000.0"
rating:
  controller:
    enabled: true

logging:
  level:
    com:
      zaxxer:
        hikari: debug