#---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
# h2:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
# mysql:
    url: jdbc:mysql://localhost:3306/KS_SPODA_DB_DEV?allowPublicKeyRetrieval=true&useSSL=false # URL DEV
    username: spoda_dev_usr1 # DEV
    password: pass_usr_1 # DEV
    driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console.enabled: true
  liquibase:
    change-log: ./database/changelog/changelog-master.yaml
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#---
---
spring:
  config:
    activate:
      on-profile: spoda
  datasource:
    url: jdbc:mysql://localhost:3306/KS_SPODA_DB?allowPublicKeyRetrieval=true&useSSL=false # URL PROD
    username: ks_spoda_test_user #PROD
    password: PASS@!TEST2 #PROD
  liquibase:
    change-log: ./database/changelog/changelog-master.yaml
    contexts: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: upload-test
  datasource:
    url: jdbc:mysql://localhost:3306/KS_SPODA_UPLOAD_TEST_DB?allowPublicKeyRetrieval=true&useSSL=false # URL PROD
    username: ks_spoda_test_user #PROD
    password: PASS@!TEST2 #PROD
  liquibase:
    change-log: ./database/changelog/changelog-master.yaml
    contexts: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true