#---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  liquibase:
    change-log: ./database/changelog/changelog-master.yaml
    contexts: dev
#---
