--liquibase formatted sql
--changeset ks-spoda:1.0

CREATE TABLE "SEASON" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "LEAGUE_ID" NUMBER(10) NOT NULL,
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE NULL,
    "IS_FINISHED" NUMBER(1) NOT NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

--ALTER TABLE USER_DATA
--ADD CONSTRAINT OPTIONAL_NAME UNIQUE (USERNAME);

--ALTER TABLE USER_DATA
--ADD CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL_ADDRESS);
--
--CREATE INDEX INDEX_PK_USER_DATA_ID ON USER_DATA (ID);

