--liquibase formatted sql
--changeset ks-spoda:1.0

create TABLE "ROUND" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "DATE" DATE NOT NULL,
    "LEAGUE_ID" DATE NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL
);


ALTER TABLE "LEAGUE" ADD ("IS_FINISHED" NUMBER(1) NOT NULL);

