--liquibase formatted sql
--changeset ks-spoda:1.0

create TABLE MATCH_DAY (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DATE DATE NOT NULL,
    SEASON_ID INT NOT NULL,
    LOCATION VARCHAR(100) NULL,
    SEASON_MATCH_DAY INT NOT NULL,
    IS_FINISHED BOOLEAN NULL,
    CREATION_DATE DATE NOT NULL,
    LAST_MODIFICATION_DATE DATE NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    IS_DELETED BOOLEAN NULL
);

