--liquibase formatted sql
--changeset ks-spoda:1.0

alter table LEAGUE_TABLE add column (
   PREVIOUS_RATING DECIMAL(10,2) NULL,
   MATCH_CURRENT_RATING DECIMAL(10,2) NULL
);

alter table SEASON_TABLE add column (
    PREVIOUS_RATING DECIMAL(10,2) NULL,
    MATCH_CURRENT_RATING DECIMAL(10,2) NULL
);

alter table MATCH_DAY_TABLE add column (
    PREVIOUS_RATING DECIMAL(10,2) NULL,
    MATCH_CURRENT_RATING DECIMAL(10,2) NULL
);

update LEAGUE_TABLE set PREVIOUS_RATING = CURRENT_RATING;
update SEASON_TABLE set PREVIOUS_RATING = CURRENT_RATING;
update MATCH_DAY_TABLE set PREVIOUS_RATING = CURRENT_RATING;