--liquibase formatted sql
--changeset ks-spoda:1.0


create TABLE "LEAGUE_TABLE_ROW" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "LEAGUE_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "MATCHES" NUMBER(5) NOT NULL,
    "RATING" NUMBER(10,2) NULL,
    "POINTS_TOTAL" NUMBER(10,2) NOT NULL,
    "WINS" NUMBER(5) NOT NULL,
    "DRAWS" NUMBER(5) NOT NULL,
    "LOSES" NUMBER(5) NOT NULL,
    "GOALS_SCORED" NUMBER(5) NOT NULL,
    "GOALS_CONCEDED" NUMBER(5) NOT NULL,
    "PLAYER_FORM" VARCHAR(10) NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "SEASON_TABLE_ROW" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "SEASON_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "MATCHES" NUMBER(5) NOT NULL,
    "RATING" NUMBER(10,2) NULL,
    "POINTS_TOTAL" NUMBER(10,2) NOT NULL,
    "WINS" NUMBER(5) NOT NULL,
    "DRAWS" NUMBER(5) NOT NULL,
    "LOSES" NUMBER(5) NOT NULL,
    "GOALS_SCORED" NUMBER(5) NOT NULL,
    "GOALS_CONCEDED" NUMBER(5) NOT NULL,
    "PLAYER_FORM" VARCHAR(10) NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);