--liquibase formatted sql
--changeset ks-spoda:1.0

CREATE TABLE "SEASON" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "LEAGUE_ID" NUMBER(10) NOT NULL,
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE NULL,
    "INITIAL_RATING" NUMBER(10,2),
    "COUNTING_POINTS_METHOD" VARCHAR(50),
    "IS_FINISHED" NUMBER(1) NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

