--liquibase formatted sql
--changeset ks-spoda:1.0

create TABLE SEASON (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LEAGUE_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    INITIAL_RATING DECIMAL(10,2) NULL,
    IS_FINISHED BOOLEAN NULL,
    POINT_COUNTING_METHOD VARCHAR(20) NOT NULL,
    RATING_TYPE  VARCHAR(10) NULL,
    LEAGUE_SEASON_COUNT INT NOT NULL,
    CREATION_DATE DATE NOT NULL,
    LAST_MODIFICATION_DATE DATE NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    IS_DELETED BOOLEAN NULL
);
