--liquibase formatted sql
--changeset ks-spoda:1.0

create TABLE "MATCH" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "MATCH_DAY_ID" NUMBER(10) NOT NULL,
    "MATCH_TIME" DATE NOT NULL,
    "HOME_TEAM_ID" NUMBER(10) NOT NULL,
    "AWAY_TEAM_ID" NUMBER(10) NOT NULL,
    "HOME_GOALS" NUMBER(2) NOT NULL,
    "AWAY_GOALS" NUMBER(2) NOT NULL,
    "IS_FINISHED" NUMBER(1) NULL,
    "TYPE" VARCHAR (10) NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);


create TABLE "MATCH_TEAM" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "FIRST_PLAYER_ID" NUMBER(10) NOT NULL,
    "SECOND_PLAYER_ID" NUMBER(10) NULL,
    "GAME_TEAM_ID" NUMBER(10) NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "PLAYER" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(30) NOT NULL,
    "ALIAS" VARCHAR(30) NULL,
    "PLAYER_IMG" BLOB NULL,
    "STATUS" VARCHAR(10) NULL,
    "DESCRIPTION" VARCHAR(200) NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "GAME_TEAM" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "ALIAS" VARCHAR(50) NULL,
    "OVERALL_RATING" NUMBER(10) NOT NULL,
    "BADGE_IMG" BLOB NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "SEASON_MATCH_HISTORICAL_RATING" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "MATCH_ID" NUMBER(10) NOT NULL,
    "SEASON_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "RATING_BEFORE_MATCH" NUMBER(10,2) NOT NULL,
    "RATING_AFTER_MATCH" NUMBER(10,2) NOT NULL,
    "GOALS_SCORED" NUMBER(2) NOT NULL,
    "GOALS_CONCEDED" NUMBER(2) NOT NULL,
    "RATING_MODE" VARCHAR(10) NOT NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "SEASON_RATING" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "SEASON_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "CURRENT_RATING" NUMBER(10,2) NOT NULL,
    "PREVIOUS_RATING" NUMBER(10,2) NOT NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "LEAGUE_RATING" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "LEAGUE_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "CURRENT_RATING" NUMBER(10,2) NOT NULL,
    "PREVIOUS_RATING" NUMBER(10,2) NOT NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);

create TABLE "LEAGUES_PLAYERS" (
    "ID" NUMBER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "LEAGUE_ID" NUMBER(10) NOT NULL,
    "PLAYER_ID" NUMBER(10) NOT NULL,
    "CREATION_DATE" DATE NOT NULL,
    "LAST_MODIFICATION_DATE" DATE NOT NULL,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "IS_DELETED" NUMBER(1) NULL
);


